runtime: python39

entrypoint: gunicorn -b :$PORT run:flask_app

handlers:
- url: /static
  static_dir: app/static

- url: /.*
  script: auto

env_variables:
  CLOUD_STORAGE_BUCKET: "delta-sigma-phi-website.appspot.com"