"""Added field for event type in Event table

Revision ID: 0067e7b1ecea
Revises: ce85aaf77374
Create Date: 2024-01-03 11:47:18.017883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0067e7b1ecea'
down_revision = 'ce85aaf77374'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_type', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('event_type')

    # ### end Alembic commands ###
