"""Changed can_create_calendar_events to canCreatEvents

Revision ID: b1dde34626f9
Revises: 65e4d0ff6573
Create Date: 2024-01-07 21:40:16.048442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1dde34626f9'
down_revision = '65e4d0ff6573'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('canCreateEvents', sa.Boolean(), nullable=False))
        batch_op.drop_column('can_create_calendar_events')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('can_create_calendar_events', sa.BOOLEAN(), nullable=False))
        batch_op.drop_column('canCreateEvents')

    # ### end Alembic commands ###
