"""Added new fields to calendar event

Revision ID: ce85aaf77374
Revises: ba61724cf1d5
Create Date: 2024-01-02 17:59:28.749340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce85aaf77374'
down_revision = 'ba61724cf1d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('end', sa.DateTime(), nullable=False))
        batch_op.drop_column('start_time')
        batch_op.drop_column('end_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end_time', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('start_time', sa.DATETIME(), nullable=False))
        batch_op.drop_column('end')
        batch_op.drop_column('start')

    # ### end Alembic commands ###
